spring:
  application:
    name: fit_health
  profiles:
    active: dev  # ?? ??? ?? dev ?? prod? ??

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/fit_healthDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fit
    password: 7961

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 7961
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: 8F7Cp/J9argI/frLc9onvqniYPJ/4MPdcM+Ci3L7iN5tnAgYDwFTJHzWxrr2RA0ejzMX9tnxfc8fVyGulCr5Xg==
  expiration: 3000 #분단위

oauth:
  kakao:
    client-id: da3b2a4c2ffd133e7d6f97b803e58ede #카카오 REST API key
    redirect-uri: http://localhost:5173/oauth/kakao/redirect
    redirect-delete-uri: http://localhost:5173/oauth/kakao/redirect/delete

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: RDB URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_pass

  jpa:
    hibernate:
      ddl-auto: validate  # ??????? validate ?? none ??
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true